SET HEADING ON;

-- 1. Información de la factura 22872
SELECT 'FACTURA 22872:' AS INFO FROM RDB$DATABASE;
SELECT ID, FOLIO, NOMBRE, SUBTOTAL, TOTAL, ESTA_CANCELADO, TOTAL_CREDITO,
       CAST(CREADO_EN AS DATE) AS FECHA_CREACION
FROM VENTATICKETS
WHERE FOLIO = 22872;

-- 2. Facturas del 31 de enero - totales
SELECT 'RESUMEN 31 ENERO:' AS INFO FROM RDB$DATABASE;
SELECT COUNT(*) AS TOTAL_FACTURAS,
       SUM(TOTAL) AS TOTAL_VENTAS,
       SUM(CASE WHEN ESTA_CANCELADO = 1 THEN TOTAL ELSE 0 END) AS TOTAL_CANCELADAS,
       SUM(CASE WHEN ESTA_CANCELADO = 0 THEN TOTAL ELSE 0 END) AS TOTAL_NO_CANCELADAS
FROM VENTATICKETS
WHERE CAST(CREADO_EN AS DATE) = '2026-01-31'
  AND FOLIO > 0;

-- 3. Facturas canceladas del 31 de enero (creadas el 31)
SELECT 'CANCELADAS DEL 31 (creadas el 31):' AS INFO FROM RDB$DATABASE;
SELECT FOLIO, NOMBRE, TOTAL, CAST(CREADO_EN AS DATE) AS FECHA_CREACION
FROM VENTATICKETS
WHERE CAST(CREADO_EN AS DATE) = '2026-01-31'
  AND ESTA_CANCELADO = 1
  AND FOLIO > 0
ORDER BY FOLIO;

-- 4. Facturas de OTROS DÍAS canceladas (que podrían afectar el 31)
SELECT 'CANCELADAS DE OTROS DIAS (como la 22872):' AS INFO FROM RDB$DATABASE;
SELECT FOLIO, NOMBRE, TOTAL, CAST(CREADO_EN AS DATE) AS FECHA_CREACION, ESTA_CANCELADO
FROM VENTATICKETS
WHERE FOLIO = 22872
   OR (CAST(CREADO_EN AS DATE) < '2026-01-31' 
       AND CAST(CREADO_EN AS DATE) >= '2026-01-25'
       AND ESTA_CANCELADO = 1
       AND FOLIO > 0)
ORDER BY FOLIO;

